In [28]:
import numpy as np
import pandas as pd
from datetime import datetime

In [112]:
f = open('./data/20111123/13301104001', 'r')        #以读方式打开文件
result = []
for line in f.readlines():                          #依次读取每行
    line = line.strip()                             #去掉每行头尾空白
    if not len(line) or line.startswith('#'):       #判断是否是空行或注释行
        continue                                    
    line = line.split(",")
    result.append(line)                             
# print(result)

In [77]:
len(result)

1429

In [100]:
df = pd.DataFrame(result)

In [102]:
df[3] =  pd.to_datetime(df[3], format='%Y%m%d%H%M%S')
df[4] = df[4].astype(float)
df[5] = df[5].astype(float)
df[8] = df[8].astype(int)
df[9] = df[9].astype(int)

In [115]:
df.dtypes

0             object
1             object
2             object
3     datetime64[ns]
4            float64
5            float64
6             object
7             object
8              int64
9              int64
10            object
11            object
12            object
dtype: object

In [104]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,15395,AYJ,13301104001,2011-11-23 00:01:34,116.288765,39.863205,428709232,146956322,0,176,0,4,50#
1,26859,AYJ,13301104001,2011-11-23 00:02:28,116.288765,39.863182,428709234,146956236,0,176,0,4,50#
2,39112,AYJ,13301104001,2011-11-23 00:03:21,116.288765,39.863186,428709225,146956251,0,176,0,4,50#
3,50949,AYJ,13301104001,2011-11-23 00:04:15,116.288780,39.863186,428709278,146956257,0,176,0,4,50#
4,2581,AYJ,13301104001,2011-11-23 00:05:08,116.288803,39.863190,428709372,146956244,0,290,0,4,50#
5,11729,AYJ,13301104001,2011-11-23 00:06:06,116.288818,39.863186,428709418,146956228,0,290,0,4,50#
6,23084,AYJ,13301104001,2011-11-23 00:07:00,116.288818,39.863182,428709430,146956214,0,290,0,4,50#
7,35297,AYJ,13301104001,2011-11-23 00:07:55,116.288834,39.863178,428709487,146956210,0,290,0,4,50#
8,47432,AYJ,13301104001,2011-11-23 00:08:50,116.288849,39.863171,428709541,146956194,0,290,0,4,50#
9,59881,AYJ,13301104001,2011-11-23 00:09:44,116.288864,39.863171,428709598,146956204,0,290,0,4,50#
10,7022,AYJ,13301104001,2011-11-23 00:10:40,116.288864,39.863171,428709599,146956174,0,290,0,4,50#
11,17236,AYJ,13301104001,2011-11-23 00:11:34,116.288849,39.863174,428709549,146956202,0,290,0,4,50#
12,28595,AYJ,13301104001,2011-11-23 00:12:28,116.288864,39.863174,428709604,146956206,0,290,0,4,50#
13,53015,AYJ,13301104001,2011-11-23 00:14:15,116.288849,39.863174,428709533,146956186,0,290,0,4,50#
14,2729,AYJ,13301104001,2011-11-23 00:15:09,116.288849,39.863178,428709556,146956232,0,290,0,4,50#
15,11582,AYJ,13301104001,2011-11-23 00:16:04,116.288849,39.863178,428709524,146956217,0,290,0,4,50#
16,22264,AYJ,13301104001,2011-11-23 00:16:58,116.288864,39.863171,428709574,146956179,0,290,0,4,50#
17,34536,AYJ,13301104001,2011-11-23 00:17:52,116.288887,39.863171,428709682,146956197,0,106,0,4,50#
18,46863,AYJ,13301104001,2011-11-23 00:18:47,116.288864,39.863178,428709593,146956216,0,106,0,4,50#
19,58986,AYJ,13301104001,2011-11-23 00:19:42,116.288818,39.863186,428709403,146956247,0,106,0,4,50#
20,6682,AYJ,13301104001,2011-11-23 00:20:36,116.288780,39.863178,428709300,146956200,0,106,0,4,50#
21,17370,AYJ,13301104001,2011-11-23 00:21:30,116.288803,39.863178,428709386,146956230,0,106,0,4,50#
22,28504,AYJ,13301104001,2011-11-23 00:22:24,116.288765,39.863167,428709224,146956169,0,106,0,4,50#
23,40813,AYJ,13301104001,2011-11-23 00:23:19,116.288780,39.863182,428709266,146956245,0,106,0,4,50#
24,52999,AYJ,13301104001,2011-11-23 00:24:13,116.288818,39.863197,428709430,146956301,0,106,0,4,50#
25,2191,AYJ,13301104001,2011-11-23 00:25:07,116.288849,39.863186,428709548,146956260,0,106,0,4,50#
26,10698,AYJ,13301104001,2011-11-23 00:26:00,116.288933,39.863194,428709866,146956273,0,90,0,4,50#
27,38468,AYJ,13301104001,2011-11-23 00:26:10,116.288864,39.863171,428709572,146956182,0,90,0,4,50#
28,21616,AYJ,13301104001,2011-11-23 00:26:55,116.288902,39.863186,428709735,146956247,0,90,0,4,50#
29,33800,AYJ,13301104001,2011-11-23 00:27:48,116.288887,39.863178,428709685,146956216,0,90,0,4,50#
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1399,14507,AYJ,13301104001,2011-11-23 23:31:08,116.354866,39.855171,428953407,146927118,0,234,0,4,50#
1400,28093,AYJ,13301104001,2011-11-23 23:32:03,116.354866,39.855183,428953387,146927170,0,234,0,4,50#
1401,41664,AYJ,13301104001,2011-11-23 23:32:56,116.354866,39.855179,428953408,146927156,0,234,0,4,50#
1402,55266,AYJ,13301104001,2011-11-23 23:33:50,116.354851,39.855179,428953349,146927161,0,234,0,4,50#
1403,68960,AYJ,13301104001,2011-11-23 23:34:43,116.354851,39.855179,428953345,146927169,0,234,0,4,50#
1404,21550,AYJ,13301104001,2011-11-23 23:36:32,116.354851,39.855175,428953369,146927157,0,234,0,4,50#
1405,35054,AYJ,13301104001,2011-11-23 23:37:27,116.354851,39.855167,428953337,146927114,0,234,0,4,50#
1406,48552,AYJ,13301104001,2011-11-23 23:38:21,116.354851,39.855164,428953330,146927090,0,234,0,4,50#
1407,62257,AYJ,13301104001,2011-11-23 23:39:16,116.354851,39.855160,428953353,146927094,0,234,0,4,50#
1408,3084,AYJ,13301104001,2011-11-23 23:40:10,116.354851,39.855156,428953368,146927085,0,234,0,4,50#
1409,13890,AYJ,13301104001,2011-11-23 23:41:05,116.354851,39.855156,428953333,146927064,0,234,0,4,50#
1410,27974,AYJ,13301104001,2011-11-23 23:41:59,116.354851,39.855152,428953349,146927044,0,234,0,4,50#
1411,41326,AYJ,13301104001,2011-11-23 23:42:55,116.354851,39.855148,428953339,146927048,0,234,0,4,50#
1412,54762,AYJ,13301104001,2011-11-23 23:43:49,116.354835,39.855145,428953313,146927036,0,234,0,4,50#
1413,68150,AYJ,13301104001,2011-11-23 23:44:43,116.354851,39.855145,428953333,146927044,0,234,0,4,50#
1414,7500,AYJ,13301104001,2011-11-23 23:45:36,116.354866,39.855152,428953410,146927062,0,234,0,4,50#
1415,19838,AYJ,13301104001,2011-11-23 23:46:30,116.354866,39.855156,428953419,146927065,0,234,0,4,50#
1416,33267,AYJ,13301104001,2011-11-23 23:47:24,116.354866,39.855152,428953423,146927063,0,234,0,4,50#
1417,46541,AYJ,13301104001,2011-11-23 23:48:18,116.354851,39.855145,428953337,146927025,0,234,0,4,50#
1418,59923,AYJ,13301104001,2011-11-23 23:49:11,116.354835,39.855129,428953298,146926976,0,234,0,4,50#
1419,1535,AYJ,13301104001,2011-11-23 23:50:05,116.354851,39.855129,428953367,146926985,0,234,0,4,50#
1420,12136,AYJ,13301104001,2011-11-23 23:50:59,116.354835,39.855125,428953294,146926961,0,234,0,4,50#
1421,25979,AYJ,13301104001,2011-11-23 23:51:53,116.354835,39.855125,428953313,146926944,0,234,0,4,50#
1422,39639,AYJ,13301104001,2011-11-23 23:52:48,116.354835,39.855118,428953283,146926919,0,234,0,4,50#
1423,53725,AYJ,13301104001,2011-11-23 23:53:44,116.354851,39.855118,428953360,146926938,0,234,0,4,50#
1424,67330,AYJ,13301104001,2011-11-23 23:54:40,116.354851,39.855110,428953365,146926908,0,234,0,4,50#
1425,20044,AYJ,13301104001,2011-11-23 23:56:30,116.354851,39.855110,428953345,146926894,0,234,0,4,50#
1426,33431,AYJ,13301104001,2011-11-23 23:57:24,116.354851,39.855106,428953354,146926884,0,234,0,4,50#
1427,46653,AYJ,13301104001,2011-11-23 23:58:18,116.354851,39.855110,428953334,146926913,0,234,0,4,50#
1428,60335,AYJ,13301104001,2011-11-23 23:59:12,116.354866,39.855110,428953405,146926918,0,234,0,4,50#

In [110]:
#五环内
df = df[df.apply(lambda x: x[4] > 116.2129590000 and x[4] < 116.5590580000, axis=1)]
df = df[df.apply(lambda x: x[5] > 39.7645780000 and x[5] < 40.0293980000, axis=1)]

#重复时间
df = df.drop_duplicates(3)

#速度90
df = df[df.apply(lambda x: x[8] <= 90, axis=1)]

#驻车
df = df[df.apply(lambda x: x[10] != "3", axis=1)]

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,15395,AYJ,13301104001,2011-11-23 00:01:34,116.288765,39.863205,428709232,146956322,0,176,0,4,50#
1,26859,AYJ,13301104001,2011-11-23 00:02:28,116.288765,39.863182,428709234,146956236,0,176,0,4,50#
2,39112,AYJ,13301104001,2011-11-23 00:03:21,116.288765,39.863186,428709225,146956251,0,176,0,4,50#
3,50949,AYJ,13301104001,2011-11-23 00:04:15,116.288780,39.863186,428709278,146956257,0,176,0,4,50#
4,2581,AYJ,13301104001,2011-11-23 00:05:08,116.288803,39.863190,428709372,146956244,0,290,0,4,50#
5,11729,AYJ,13301104001,2011-11-23 00:06:06,116.288818,39.863186,428709418,146956228,0,290,0,4,50#
6,23084,AYJ,13301104001,2011-11-23 00:07:00,116.288818,39.863182,428709430,146956214,0,290,0,4,50#
7,35297,AYJ,13301104001,2011-11-23 00:07:55,116.288834,39.863178,428709487,146956210,0,290,0,4,50#
8,47432,AYJ,13301104001,2011-11-23 00:08:50,116.288849,39.863171,428709541,146956194,0,290,0,4,50#
9,59881,AYJ,13301104001,2011-11-23 00:09:44,116.288864,39.863171,428709598,146956204,0,290,0,4,50#
10,7022,AYJ,13301104001,2011-11-23 00:10:40,116.288864,39.863171,428709599,146956174,0,290,0,4,50#
11,17236,AYJ,13301104001,2011-11-23 00:11:34,116.288849,39.863174,428709549,146956202,0,290,0,4,50#
12,28595,AYJ,13301104001,2011-11-23 00:12:28,116.288864,39.863174,428709604,146956206,0,290,0,4,50#
13,53015,AYJ,13301104001,2011-11-23 00:14:15,116.288849,39.863174,428709533,146956186,0,290,0,4,50#
14,2729,AYJ,13301104001,2011-11-23 00:15:09,116.288849,39.863178,428709556,146956232,0,290,0,4,50#
15,11582,AYJ,13301104001,2011-11-23 00:16:04,116.288849,39.863178,428709524,146956217,0,290,0,4,50#
16,22264,AYJ,13301104001,2011-11-23 00:16:58,116.288864,39.863171,428709574,146956179,0,290,0,4,50#
17,34536,AYJ,13301104001,2011-11-23 00:17:52,116.288887,39.863171,428709682,146956197,0,106,0,4,50#
18,46863,AYJ,13301104001,2011-11-23 00:18:47,116.288864,39.863178,428709593,146956216,0,106,0,4,50#
19,58986,AYJ,13301104001,2011-11-23 00:19:42,116.288818,39.863186,428709403,146956247,0,106,0,4,50#
20,6682,AYJ,13301104001,2011-11-23 00:20:36,116.288780,39.863178,428709300,146956200,0,106,0,4,50#
21,17370,AYJ,13301104001,2011-11-23 00:21:30,116.288803,39.863178,428709386,146956230,0,106,0,4,50#
22,28504,AYJ,13301104001,2011-11-23 00:22:24,116.288765,39.863167,428709224,146956169,0,106,0,4,50#
23,40813,AYJ,13301104001,2011-11-23 00:23:19,116.288780,39.863182,428709266,146956245,0,106,0,4,50#
24,52999,AYJ,13301104001,2011-11-23 00:24:13,116.288818,39.863197,428709430,146956301,0,106,0,4,50#
25,2191,AYJ,13301104001,2011-11-23 00:25:07,116.288849,39.863186,428709548,146956260,0,106,0,4,50#
26,10698,AYJ,13301104001,2011-11-23 00:26:00,116.288933,39.863194,428709866,146956273,0,90,0,4,50#
27,38468,AYJ,13301104001,2011-11-23 00:26:10,116.288864,39.863171,428709572,146956182,0,90,0,4,50#
28,21616,AYJ,13301104001,2011-11-23 00:26:55,116.288902,39.863186,428709735,146956247,0,90,0,4,50#
29,33800,AYJ,13301104001,2011-11-23 00:27:48,116.288887,39.863178,428709685,146956216,0,90,0,4,50#
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1399,14507,AYJ,13301104001,2011-11-23 23:31:08,116.354866,39.855171,428953407,146927118,0,234,0,4,50#
1400,28093,AYJ,13301104001,2011-11-23 23:32:03,116.354866,39.855183,428953387,146927170,0,234,0,4,50#
1401,41664,AYJ,13301104001,2011-11-23 23:32:56,116.354866,39.855179,428953408,146927156,0,234,0,4,50#
1402,55266,AYJ,13301104001,2011-11-23 23:33:50,116.354851,39.855179,428953349,146927161,0,234,0,4,50#
1403,68960,AYJ,13301104001,2011-11-23 23:34:43,116.354851,39.855179,428953345,146927169,0,234,0,4,50#
1404,21550,AYJ,13301104001,2011-11-23 23:36:32,116.354851,39.855175,428953369,146927157,0,234,0,4,50#
1405,35054,AYJ,13301104001,2011-11-23 23:37:27,116.354851,39.855167,428953337,146927114,0,234,0,4,50#
1406,48552,AYJ,13301104001,2011-11-23 23:38:21,116.354851,39.855164,428953330,146927090,0,234,0,4,50#
1407,62257,AYJ,13301104001,2011-11-23 23:39:16,116.354851,39.855160,428953353,146927094,0,234,0,4,50#
1408,3084,AYJ,13301104001,2011-11-23 23:40:10,116.354851,39.855156,428953368,146927085,0,234,0,4,50#
1409,13890,AYJ,13301104001,2011-11-23 23:41:05,116.354851,39.855156,428953333,146927064,0,234,0,4,50#
1410,27974,AYJ,13301104001,2011-11-23 23:41:59,116.354851,39.855152,428953349,146927044,0,234,0,4,50#
1411,41326,AYJ,13301104001,2011-11-23 23:42:55,116.354851,39.855148,428953339,146927048,0,234,0,4,50#
1412,54762,AYJ,13301104001,2011-11-23 23:43:49,116.354835,39.855145,428953313,146927036,0,234,0,4,50#
1413,68150,AYJ,13301104001,2011-11-23 23:44:43,116.354851,39.855145,428953333,146927044,0,234,0,4,50#
1414,7500,AYJ,13301104001,2011-11-23 23:45:36,116.354866,39.855152,428953410,146927062,0,234,0,4,50#
1415,19838,AYJ,13301104001,2011-11-23 23:46:30,116.354866,39.855156,428953419,146927065,0,234,0,4,50#
1416,33267,AYJ,13301104001,2011-11-23 23:47:24,116.354866,39.855152,428953423,146927063,0,234,0,4,50#
1417,46541,AYJ,13301104001,2011-11-23 23:48:18,116.354851,39.855145,428953337,146927025,0,234,0,4,50#
1418,59923,AYJ,13301104001,2011-11-23 23:49:11,116.354835,39.855129,428953298,146926976,0,234,0,4,50#
1419,1535,AYJ,13301104001,2011-11-23 23:50:05,116.354851,39.855129,428953367,146926985,0,234,0,4,50#
1420,12136,AYJ,13301104001,2011-11-23 23:50:59,116.354835,39.855125,428953294,146926961,0,234,0,4,50#
1421,25979,AYJ,13301104001,2011-11-23 23:51:53,116.354835,39.855125,428953313,146926944,0,234,0,4,50#
1422,39639,AYJ,13301104001,2011-11-23 23:52:48,116.354835,39.855118,428953283,146926919,0,234,0,4,50#
1423,53725,AYJ,13301104001,2011-11-23 23:53:44,116.354851,39.855118,428953360,146926938,0,234,0,4,50#
1424,67330,AYJ,13301104001,2011-11-23 23:54:40,116.354851,39.855110,428953365,146926908,0,234,0,4,50#
1425,20044,AYJ,13301104001,2011-11-23 23:56:30,116.354851,39.855110,428953345,146926894,0,234,0,4,50#
1426,33431,AYJ,13301104001,2011-11-23 23:57:24,116.354851,39.855106,428953354,146926884,0,234,0,4,50#
1427,46653,AYJ,13301104001,2011-11-23 23:58:18,116.354851,39.855110,428953334,146926913,0,234,0,4,50#
1428,60335,AYJ,13301104001,2011-11-23 23:59:12,116.354866,39.855110,428953405,146926918,0,234,0,4,50#